#!/usr/bin/env bash
set -euo pipefail

APP_NAME="vboard-node"
DEFAULT_ACTION="install"
DEFAULT_MODE="machine"
DEFAULT_KERNEL="sing-box"
DEFAULT_KERNEL_MODE="embedded"
DEFAULT_INTERVAL="30"
DEFAULT_INSTALL_DIR="/usr/local/bin"
DEFAULT_CONFIG_DIR="/etc/vboard-node"
DEFAULT_RUNTIME_DIR="/var/lib/vboard-node"
DEFAULT_USER="root"
DEFAULT_BINARY_URL=""
DEFAULT_RELEASE_BASE="https://github.com/unixsun/vboard-node/releases"
DEFAULT_RELEASE_VERSION="latest"
DEFAULT_SING_BOX_VERSION=""
DEFAULT_STATS_API="127.0.0.1:10085"

ACTION="${DEFAULT_ACTION}"
MODE="${DEFAULT_MODE}"
PANEL_URL=""
TOKEN=""
MACHINE_ID=""
KERNEL="${DEFAULT_KERNEL}"
KERNEL_MODE="${VBOARD_NODE_KERNEL_MODE:-${DEFAULT_KERNEL_MODE}}"
INTERVAL="${DEFAULT_INTERVAL}"
INSTALL_DIR="${DEFAULT_INSTALL_DIR}"
CONFIG_DIR="${DEFAULT_CONFIG_DIR}"
RUNTIME_DIR="${DEFAULT_RUNTIME_DIR}"
RUN_USER="${DEFAULT_USER}"
BINARY_URL="${VBOARD_NODE_BINARY_URL:-${DEFAULT_BINARY_URL}}"
RELEASE_BASE="${VBOARD_NODE_RELEASE_BASE:-${DEFAULT_RELEASE_BASE}}"
RELEASE_VERSION="${VBOARD_NODE_RELEASE_VERSION:-${DEFAULT_RELEASE_VERSION}}"
BINARY_SHA256="${VBOARD_NODE_BINARY_SHA256:-}"
CHECKSUM_URL="${VBOARD_NODE_CHECKSUM_URL:-}"
SKIP_CHECKSUM="${VBOARD_NODE_SKIP_CHECKSUM:-false}"
ENABLE_KERNEL="false"
ENABLE_UPGRADE="${VBOARD_NODE_ENABLE_UPGRADE:-false}"
SING_BOX_BIN="sing-box"
SING_BOX_BIN_SET="false"
STATS_API="${VBOARD_NODE_STATS_API:-${DEFAULT_STATS_API}}"
INSTALL_SING_BOX="${VBOARD_NODE_INSTALL_SING_BOX:-auto}"
SING_BOX_VERSION="${VBOARD_NODE_SING_BOX_VERSION:-${DEFAULT_SING_BOX_VERSION}}"
SELF_TEST="${VBOARD_NODE_SELF_TEST:-true}"
CERTIFICATE_PATH="${VBOARD_NODE_CERTIFICATE_PATH:-}"
PRIVATE_KEY_PATH="${VBOARD_NODE_PRIVATE_KEY_PATH:-}"
SERVICE_FILE="/etc/systemd/system/${APP_NAME}.service"
UPGRADE_SERVICE_FILE="/etc/systemd/system/${APP_NAME}-upgrade.service"
ENV_FILE="${CONFIG_DIR}/vboard-node.env"
BACKUP_DIR="${CONFIG_DIR}/backups"
BACKUP_PATH=""
TMP_DIR=""
ROLLBACK_READY="false"
SERVICE_EXISTED="false"
STAGED_BINARY=""

usage() {
  cat <<'USAGE'
Install and manage vboard-node.

Usage:
  install.sh [install] --mode machine --panel <url> --token <token> --machine-id <sid> [options]
  install.sh upgrade [--version <version>] [download options]
  install.sh status
  install.sh uninstall

Required:
  --panel <url>          VBoard API URL, for example https://panel.example.com or http://10.0.0.1:8080
  --token <token>        Server token generated by the panel
  --machine-id <sid>     Server SID / machine_id

Options:
  --mode <mode>          Runtime mode, currently only machine is supported (default: machine)
  --kernel <kernel>      Kernel type: sing-box or xray-core (default: sing-box)
  --kernel-mode <mode>   Kernel runtime: embedded or external (default: embedded)
  --interval <seconds>   Sync interval in seconds (default: 30)
  --binary-url <url>     vboard-node binary download URL
  --release-base <url>   GitHub Releases base URL, ending with /releases
  --version <version>    Release tag or latest (default: latest)
  --binary-sha256 <hex>  Expected SHA256 for the binary
  --checksum-url <url>   SHA256 file URL (default: <binary-url>.sha256)
  --skip-checksum        Allow an unsigned download (not recommended)
  --install-dir <path>   Binary install directory (default: /usr/local/bin)
  --config-dir <path>    Config directory (default: /etc/vboard-node)
  --runtime-dir <path>   Runtime directory (default: /var/lib/vboard-node)
  --user <user>          systemd service user (default: root)
  --enable-kernel        Let vboard-node manage the selected kernel process
  --enable-upgrade       Allow signed panel tasks to install a SHA256-pinned agent release
  --sing-box <path>      sing-box binary path (default: sing-box)
  --stats-api <addr>     sing-box V2Ray stats API address, empty disables stats config (default: 127.0.0.1:10085)
  --certificate-path     TLS server certificate chain path shared by this server's TLS nodes
  --key-path             TLS server private key path shared by this server's TLS nodes
  --install-sing-box     Download sing-box when it is missing
  --no-install-sing-box  Do not install sing-box automatically
  --sing-box-version <v> Install a specific sing-box version, for example v1.12.0
  --skip-self-test       Skip the one-shot connection/config/kernel test before starting systemd
  --help, -h             Show this help

Examples:
  curl -fsSL https://raw.githubusercontent.com/unixsun/vboard-node/main/install.sh | sudo bash -s -- \
    --mode machine \
    --panel https://panel.example.com \
    --token vbnode_xxx \
    --machine-id 1 \
    --kernel sing-box \
    --enable-kernel

  VBOARD_NODE_BINARY_URL=https://github.com/unixsun/vboard-node/releases/latest/download/vboard-node-linux-amd64 \
    sudo bash install.sh --panel https://panel.example.com --token vbnode_xxx --machine-id 1 --enable-kernel

  sudo bash install.sh upgrade \
    --release-base https://github.com/unixsun/vboard-node/releases \
    --version v0.1.0
USAGE
}

log() {
  printf '[vboard-node] %s\n' "$*"
}

fatal() {
  printf '[vboard-node] ERROR: %s\n' "$*" >&2
  if [ "$ROLLBACK_READY" = "true" ]; then
    rollback || true
  fi
  exit 1
}

cleanup() {
  if [ -n "$TMP_DIR" ] && [ -d "$TMP_DIR" ]; then
    rm -rf "$TMP_DIR"
  fi
}

rollback() {
  [ "$ROLLBACK_READY" = "true" ] || return 0
  log "upgrade failed; restoring backup: $BACKUP_PATH"

  systemctl stop "$APP_NAME" >/dev/null 2>&1 || true
  if [ -f "$BACKUP_PATH/${APP_NAME}" ]; then
    install -m 0755 "$BACKUP_PATH/${APP_NAME}" "${INSTALL_DIR}/${APP_NAME}"
  else
    rm -f "${INSTALL_DIR}/${APP_NAME}"
  fi
  if [ -f "$BACKUP_PATH/vboard-node.env" ]; then
    install -m 0600 "$BACKUP_PATH/vboard-node.env" "$ENV_FILE"
  else
    rm -f "$ENV_FILE"
  fi
  if [ -f "$BACKUP_PATH/${APP_NAME}.service" ]; then
    install -m 0644 "$BACKUP_PATH/${APP_NAME}.service" "$SERVICE_FILE"
  else
    rm -f "$SERVICE_FILE"
  fi

  systemctl daemon-reload >/dev/null 2>&1 || true
  if [ "$SERVICE_EXISTED" = "true" ]; then
    systemctl restart "$APP_NAME" >/dev/null 2>&1 || true
  fi
  ROLLBACK_READY="false"
  log "backup restored"
}

on_error() {
  local exit_code=$?
  rollback || true
  cleanup
  exit "$exit_code"
}

trap on_error ERR
trap cleanup EXIT

need_root() {
  if [ "${EUID:-$(id -u)}" -ne 0 ]; then
    fatal "please run as root or with sudo"
  fi
}

normalize_kernel() {
  case "$1" in
    singbox|sing-box) printf 'sing-box' ;;
    xray|xray-core) printf 'xray-core' ;;
    *) printf '%s' "$1" ;;
  esac
}

parse_args() {
  if [ "$#" -gt 0 ]; then
    case "$1" in
      install|upgrade|status|uninstall)
        ACTION="$1"
        shift
        ;;
    esac
  fi
  while [ "$#" -gt 0 ]; do
    case "$1" in
      --mode|-m)
        MODE="${2:-}"
        shift 2
        ;;
      --panel|--panel-url)
        PANEL_URL="${2:-}"
        shift 2
        ;;
      --token|-t)
        TOKEN="${2:-}"
        shift 2
        ;;
      --machine-id|--sid)
        MACHINE_ID="${2:-}"
        shift 2
        ;;
      --kernel|-k)
        KERNEL="$(normalize_kernel "${2:-}")"
        shift 2
        ;;
      --kernel-mode)
        KERNEL_MODE="${2:-}"
        shift 2
        ;;
      --interval)
        INTERVAL="${2:-}"
        shift 2
        ;;
      --binary-url)
        BINARY_URL="${2:-}"
        shift 2
        ;;
      --release-base)
        RELEASE_BASE="${2:-}"
        shift 2
        ;;
      --version)
        RELEASE_VERSION="${2:-}"
        shift 2
        ;;
      --binary-sha256)
        BINARY_SHA256="${2:-}"
        shift 2
        ;;
      --checksum-url)
        CHECKSUM_URL="${2:-}"
        shift 2
        ;;
      --skip-checksum)
        SKIP_CHECKSUM="true"
        shift
        ;;
      --install-dir)
        INSTALL_DIR="${2:-}"
        shift 2
        ;;
      --config-dir)
        CONFIG_DIR="${2:-}"
        shift 2
        ;;
      --runtime-dir)
        RUNTIME_DIR="${2:-}"
        shift 2
        ;;
      --user)
        RUN_USER="${2:-}"
        shift 2
        ;;
      --enable-kernel)
        ENABLE_KERNEL="true"
        shift
        ;;
      --enable-upgrade)
        ENABLE_UPGRADE="true"
        shift
        ;;
      --sing-box)
        SING_BOX_BIN="${2:-}"
        SING_BOX_BIN_SET="true"
        shift 2
        ;;
      --stats-api)
        STATS_API="${2:-}"
        shift 2
        ;;
      --certificate-path)
        CERTIFICATE_PATH="${2:-}"
        shift 2
        ;;
      --key-path)
        PRIVATE_KEY_PATH="${2:-}"
        shift 2
        ;;
      --install-sing-box)
        INSTALL_SING_BOX="true"
        shift
        ;;
      --no-install-sing-box)
        INSTALL_SING_BOX="false"
        shift
        ;;
      --sing-box-version)
        SING_BOX_VERSION="${2:-}"
        shift 2
        ;;
      --skip-self-test)
        SELF_TEST="false"
        shift
        ;;
      --help|-h)
        usage
        exit 0
        ;;
      *)
        fatal "unknown argument: $1"
        ;;
    esac
  done
}

validate_args() {
  [ "$MODE" = "machine" ] || fatal "only --mode machine is currently supported"
  [ -n "$PANEL_URL" ] || fatal "--panel is required"
  [ -n "$TOKEN" ] || fatal "--token is required"
  [ -n "$MACHINE_ID" ] || fatal "--machine-id is required"
  case "$KERNEL" in
    sing-box|xray-core) ;;
    *) fatal "--kernel must be sing-box or xray-core" ;;
  esac
  case "$KERNEL_MODE" in
    embedded|external) ;;
    *) fatal "--kernel-mode must be embedded or external" ;;
  esac
  case "$INTERVAL" in
    ''|*[!0-9]*) fatal "--interval must be a number" ;;
  esac
  [ "$INTERVAL" -ge 5 ] || fatal "--interval must be >= 5"
  case "$INSTALL_SING_BOX" in
    auto|true|false) ;;
    *) fatal "--install-sing-box mode must be auto, true, or false" ;;
  esac
  case "$SELF_TEST" in
    true|false) ;;
    *) fatal "--skip-self-test / VBOARD_NODE_SELF_TEST must resolve to true or false" ;;
  esac
  case "$SKIP_CHECKSUM" in
    true|false) ;;
    *) fatal "--skip-checksum / VBOARD_NODE_SKIP_CHECKSUM must resolve to true or false" ;;
  esac
  case "$ENABLE_UPGRADE" in
    true|false) ;;
    *) fatal "--enable-upgrade / VBOARD_NODE_ENABLE_UPGRADE must resolve to true or false" ;;
  esac
  if { [ -n "$CERTIFICATE_PATH" ] && [ -z "$PRIVATE_KEY_PATH" ]; } ||
     { [ -z "$CERTIFICATE_PATH" ] && [ -n "$PRIVATE_KEY_PATH" ]; }; then
    fatal "--certificate-path and --key-path must be configured together"
  fi
}

refresh_paths() {
  ENV_FILE="${CONFIG_DIR}/vboard-node.env"
  BACKUP_DIR="${CONFIG_DIR}/backups"
}

read_env_value() {
  local key="$1"
  [ -f "$ENV_FILE" ] || return 0
  sed -n "s/^${key}=//p" "$ENV_FILE" | tail -n 1
}

load_existing_config() {
  refresh_paths
  [ -f "$ENV_FILE" ] || fatal "existing config not found: $ENV_FILE"

  [ -n "$PANEL_URL" ] || PANEL_URL="$(read_env_value PANEL_URL)"
  [ -n "$TOKEN" ] || TOKEN="$(read_env_value SERVER_TOKEN)"
  [ -n "$MACHINE_ID" ] || MACHINE_ID="$(read_env_value MACHINE_ID)"
  KERNEL="$(read_env_value KERNEL)"
  KERNEL="${KERNEL:-$DEFAULT_KERNEL}"
  KERNEL_MODE="$(read_env_value KERNEL_MODE)"
  KERNEL_MODE="${KERNEL_MODE:-$DEFAULT_KERNEL_MODE}"
  INTERVAL="$(read_env_value INTERVAL)"
  INTERVAL="${INTERVAL:-$DEFAULT_INTERVAL}"
  RUNTIME_DIR="$(read_env_value RUNTIME_DIR)"
  RUNTIME_DIR="${RUNTIME_DIR:-$DEFAULT_RUNTIME_DIR}"
  SING_BOX_BIN="$(read_env_value SING_BOX_BIN)"
  SING_BOX_BIN="${SING_BOX_BIN:-sing-box}"
  STATS_API="$(read_env_value STATS_API)"
  ENABLE_KERNEL="$(read_env_value ENABLE_KERNEL)"
  ENABLE_KERNEL="${ENABLE_KERNEL:-false}"
  ENABLE_UPGRADE="$(read_env_value ENABLE_UPGRADE)"
  ENABLE_UPGRADE="${ENABLE_UPGRADE:-false}"
  CERTIFICATE_PATH="$(read_env_value CERTIFICATE_PATH)"
  PRIVATE_KEY_PATH="$(read_env_value PRIVATE_KEY_PATH)"
}

detect_arch() {
  local os arch
  os="$(uname -s | tr '[:upper:]' '[:lower:]')"
  arch="$(uname -m)"
  case "$arch" in
    x86_64|amd64) arch="amd64" ;;
    aarch64|arm64) arch="arm64" ;;
    *) fatal "unsupported architecture: $arch" ;;
  esac
  printf '%s-%s' "$os" "$arch"
}

resolve_download_url() {
  if [ -n "$BINARY_URL" ]; then
    return 0
  fi
  [ -n "$RELEASE_BASE" ] || return 0

  local artifact
  artifact="${APP_NAME}-$(detect_arch)"
  RELEASE_BASE="${RELEASE_BASE%/}"
  if [ "$RELEASE_VERSION" = "latest" ]; then
    BINARY_URL="${RELEASE_BASE}/latest/download/${artifact}"
  else
    BINARY_URL="${RELEASE_BASE}/download/${RELEASE_VERSION}/${artifact}"
  fi
}

sha256_file() {
  local file="$1"
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$file" | awk '{print $1}'
    return
  fi
  if command -v shasum >/dev/null 2>&1; then
    shasum -a 256 "$file" | awk '{print $1}'
    return
  fi
  fatal "sha256sum or shasum is required"
}

resolve_expected_sha256() {
  if [ -n "$BINARY_SHA256" ]; then
    printf '%s' "$BINARY_SHA256" | tr '[:upper:]' '[:lower:]'
    return
  fi
  [ "$SKIP_CHECKSUM" = "false" ] || return 0

  local url checksum_file expected
  url="${CHECKSUM_URL:-${BINARY_URL}.sha256}"
  checksum_file="${TMP_DIR}/binary.sha256"
  log "downloading checksum from $url" >&2
  curl -fsSL "$url" -o "$checksum_file"
  expected="$(awk 'NF {print $1; exit}' "$checksum_file" | tr '[:upper:]' '[:lower:]')"
  printf '%s' "$expected"
}

verify_binary_checksum() {
  local file="$1"
  if [ "$SKIP_CHECKSUM" = "true" ]; then
    log "WARNING: binary checksum verification was explicitly disabled"
    return
  fi

  local expected actual
  expected="$(resolve_expected_sha256)"
  case "$expected" in
    ''|*[!0-9a-f]*) fatal "invalid or missing binary SHA256" ;;
  esac
  [ "${#expected}" -eq 64 ] || fatal "binary SHA256 must contain 64 hexadecimal characters"
  actual="$(sha256_file "$file")"
  [ "$actual" = "$expected" ] || fatal "binary checksum mismatch: expected $expected, got $actual"
  log "binary SHA256 verified"
}

stage_binary() {
  mkdir -p "$INSTALL_DIR"
  TMP_DIR="${TMP_DIR:-$(mktemp -d)}"
  local staged="${TMP_DIR}/${APP_NAME}"
  resolve_download_url
  if [ -n "$BINARY_URL" ]; then
    log "downloading binary from $BINARY_URL"
    curl -fsSL "$BINARY_URL" -o "$staged"
    verify_binary_checksum "$staged"
    chmod 0755 "$staged"
    "$staged" --help >/dev/null
    STAGED_BINARY="$staged"
    return
  fi

  if command -v "$APP_NAME" >/dev/null 2>&1; then
    local existing
    existing="$(command -v "$APP_NAME")"
    log "using existing binary: $existing"
    cp "$existing" "$staged"
    chmod 0755 "$staged"
    STAGED_BINARY="$staged"
    return
  fi
  if [ -x "./${APP_NAME}" ]; then
    log "using local binary: ./${APP_NAME}"
    cp "./${APP_NAME}" "$staged"
    chmod 0755 "$staged"
    STAGED_BINARY="$staged"
    return
  fi

  fatal "missing binary. Provide --binary-url/--release-base or install vboard-node in PATH first. Detected platform: $(detect_arch)"
}

backup_existing_state() {
  mkdir -p "$BACKUP_DIR"
  BACKUP_PATH="$(mktemp -d "${BACKUP_DIR}/$(date -u +%Y%m%dT%H%M%SZ)-XXXXXX")"
  chmod 0700 "$BACKUP_PATH"

  if [ -x "${INSTALL_DIR}/${APP_NAME}" ]; then
    cp "${INSTALL_DIR}/${APP_NAME}" "$BACKUP_PATH/${APP_NAME}"
  fi
  if [ -f "$ENV_FILE" ]; then
    cp "$ENV_FILE" "$BACKUP_PATH/vboard-node.env"
  fi
  if [ -f "$SERVICE_FILE" ]; then
    cp "$SERVICE_FILE" "$BACKUP_PATH/${APP_NAME}.service"
    SERVICE_EXISTED="true"
  fi
  ROLLBACK_READY="true"
}

install_staged_binary() {
  local staged="$1"
  systemctl stop "$APP_NAME" >/dev/null 2>&1 || true
  install -m 0755 "$staged" "${INSTALL_DIR}/${APP_NAME}"
}

resolve_binary() {
  local binary="$1"
  if command -v "$binary" >/dev/null 2>&1; then
    command -v "$binary"
    return 0
  fi
  if [ -x "$binary" ]; then
    printf '%s\n' "$binary"
    return 0
  fi
  return 1
}

latest_sing_box_tag() {
  curl -fsSL https://api.github.com/repos/SagerNet/sing-box/releases/latest |
    sed -n 's/.*"tag_name"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' |
    head -n 1
}

install_sing_box_binary() {
  command -v tar >/dev/null 2>&1 || fatal "tar is required to install sing-box"

  local platform tag version asset url checksum_url tmp archive checksum_file expected actual extracted target
  platform="$(detect_arch)"
  case "$platform" in
    linux-amd64|linux-arm64) ;;
    *) fatal "sing-box auto install only supports linux-amd64 and linux-arm64, got: $platform" ;;
  esac

  tag="$SING_BOX_VERSION"
  if [ -z "$tag" ]; then
    log "resolving latest sing-box release"
    tag="$(latest_sing_box_tag)"
  fi
  [ -n "$tag" ] || fatal "could not resolve latest sing-box release"
  version="${tag#v}"
  asset="sing-box-${version}-${platform}.tar.gz"
  url="https://github.com/SagerNet/sing-box/releases/download/${tag}/${asset}"
  checksum_url="https://github.com/SagerNet/sing-box/releases/download/${tag}/sing-box-${version}-checksums.txt"
  target="${INSTALL_DIR}/sing-box"

  tmp="$(mktemp -d)"
  archive="${tmp}/${asset}"
  log "downloading sing-box from $url"
  if ! curl -fL "$url" -o "$archive"; then
    rm -rf "$tmp"
    fatal "failed to download sing-box release asset: $asset"
  fi
  if [ "$SKIP_CHECKSUM" = "false" ]; then
    checksum_file="${tmp}/sing-box-checksums.txt"
    log "downloading sing-box checksums from $checksum_url"
    curl -fsSL "$checksum_url" -o "$checksum_file" ||
      fatal "failed to download sing-box checksum manifest"
    expected="$(awk -v name="$asset" '$2 == name || $2 == "*" name {print $1; exit}' "$checksum_file")"
    [ -n "$expected" ] || fatal "sing-box checksum was not found for $asset"
    actual="$(sha256_file "$archive")"
    [ "$actual" = "$expected" ] ||
      fatal "sing-box checksum mismatch: expected $expected, got $actual"
    log "sing-box SHA256 verified"
  else
    log "WARNING: sing-box checksum verification was explicitly disabled"
  fi

  tar -xzf "$archive" -C "$tmp"
  extracted="$(find "$tmp" -type f -name sing-box | head -n 1)"
  if [ -z "$extracted" ]; then
    rm -rf "$tmp"
    fatal "sing-box binary was not found in release archive"
  fi

  mkdir -p "$INSTALL_DIR"
  cp "$extracted" "$target"
  chmod 0755 "$target"
  rm -rf "$tmp"
  SING_BOX_BIN="$target"
  log "installed sing-box: $target"
}

ensure_sing_box() {
  [ "$KERNEL" = "sing-box" ] || return 0
  if [ "$KERNEL_MODE" = "embedded" ]; then
    log "using embedded sing-box; external binary installation is not required"
    return 0
  fi

  local existing=""
  if existing="$(resolve_binary "$SING_BOX_BIN")"; then
    if [ "$SING_BOX_BIN_SET" = "false" ]; then
      SING_BOX_BIN="$existing"
    fi
    log "using sing-box: $SING_BOX_BIN"
    return 0
  fi

  if [ "$INSTALL_SING_BOX" = "false" ]; then
    if [ "$ENABLE_KERNEL" = "true" ]; then
      fatal "sing-box was not found. Install it first, pass --sing-box <path>, or remove --no-install-sing-box"
    fi
    log "sing-box not found, auto install disabled"
    return 0
  fi

  if [ "$ENABLE_KERNEL" = "true" ] || [ "$INSTALL_SING_BOX" = "true" ]; then
    install_sing_box_binary
    return 0
  fi

  log "sing-box not found, skipped because kernel management is disabled"
}

write_env_file() {
  mkdir -p "$CONFIG_DIR" "$RUNTIME_DIR"
  chmod 0750 "$CONFIG_DIR" "$RUNTIME_DIR"
  if [ "$RUN_USER" != "root" ]; then
    id "$RUN_USER" >/dev/null 2>&1 || fatal "systemd user does not exist: $RUN_USER"
    chown "$RUN_USER" "$RUNTIME_DIR"
  fi
  cat >"$ENV_FILE" <<EOF
PANEL_URL=${PANEL_URL}
SERVER_TOKEN=${TOKEN}
MACHINE_ID=${MACHINE_ID}
KERNEL=${KERNEL}
KERNEL_MODE=${KERNEL_MODE}
INTERVAL=${INTERVAL}
RUNTIME_DIR=${RUNTIME_DIR}
SING_BOX_BIN=${SING_BOX_BIN}
STATS_API=${STATS_API}
ENABLE_KERNEL=${ENABLE_KERNEL}
ENABLE_UPGRADE=${ENABLE_UPGRADE}
CERTIFICATE_PATH=${CERTIFICATE_PATH}
PRIVATE_KEY_PATH=${PRIVATE_KEY_PATH}
EOF
  chmod 0600 "$ENV_FILE"
  log "wrote config: $ENV_FILE"
}

self_test() {
  if [ "$SELF_TEST" != "true" ]; then
    log "self-test skipped"
    return 0
  fi

  local enable_flag=""
  local upgrade_flag=""
  if [ "$ENABLE_KERNEL" = "true" ]; then
    enable_flag="--enable-kernel"
  fi
  if [ "$ENABLE_UPGRADE" = "true" ]; then
    upgrade_flag="--enable-upgrade"
  fi

  log "running self-test: connect panel, fetch nodes, build config, and check kernel"
  if "${INSTALL_DIR}/${APP_NAME}" \
    --mode machine \
    --panel "$PANEL_URL" \
    --token "$TOKEN" \
    --machine-id "$MACHINE_ID" \
    --kernel "$KERNEL" \
    --kernel-mode "$KERNEL_MODE" \
    --interval "$INTERVAL" \
    --runtime-dir "$RUNTIME_DIR" \
    --sing-box "$SING_BOX_BIN" \
    --stats-api "$STATS_API" \
    --certificate-path "$CERTIFICATE_PATH" \
    --key-path "$PRIVATE_KEY_PATH" \
    $enable_flag \
    $upgrade_flag \
    --once; then
    log "self-test passed"
    return 0
  fi

  cat >&2 <<EOF
[vboard-node] ERROR: self-test failed.
[vboard-node] Installed files are kept in place for troubleshooting.
[vboard-node] Common causes:
[vboard-node]   - --panel is not reachable from this server
[vboard-node]   - --token is invalid or expired
[vboard-node]   - --machine-id does not match this server record
[vboard-node]   - sing-box is missing or the generated config is invalid
[vboard-node] You can rerun the installer with --skip-self-test, or fix the parameters and run it again.
EOF
  exit 1
}

write_systemd_service() {
  command -v systemctl >/dev/null 2>&1 || fatal "systemd is required"

  local enable_flag=""
  local upgrade_flag=""
  if [ "$ENABLE_KERNEL" = "true" ]; then
    enable_flag="--enable-kernel"
  fi
  if [ "$ENABLE_UPGRADE" = "true" ]; then
    upgrade_flag="--enable-upgrade"
  fi

  cat >"$SERVICE_FILE" <<EOF
[Unit]
Description=VBoard Node Agent
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=${RUN_USER}
EnvironmentFile=${CONFIG_DIR}/vboard-node.env
ExecStart=${INSTALL_DIR}/${APP_NAME} --mode machine --panel \${PANEL_URL} --token \${SERVER_TOKEN} --machine-id \${MACHINE_ID} --kernel \${KERNEL} --kernel-mode \${KERNEL_MODE} --interval \${INTERVAL} --runtime-dir \${RUNTIME_DIR} --sing-box \${SING_BOX_BIN} --stats-api=\${STATS_API} --certificate-path=\${CERTIFICATE_PATH} --key-path=\${PRIVATE_KEY_PATH} ${enable_flag} ${upgrade_flag}
Restart=always
RestartSec=5
LimitNOFILE=1048576
UMask=0077
NoNewPrivileges=true
PrivateTmp=true
ProtectHome=true
ProtectSystem=full
ProtectKernelTunables=true
ProtectKernelModules=true
ProtectControlGroups=true
RestrictSUIDSGID=true
LockPersonality=true
ReadWritePaths=${RUNTIME_DIR}

[Install]
WantedBy=multi-user.target
EOF

  chmod 0644 "$SERVICE_FILE"
  write_upgrade_service
  systemctl daemon-reload
  systemctl enable "$APP_NAME"
  systemctl restart --no-block "$APP_NAME"
  local attempt state
  for attempt in $(seq 1 30); do
    sleep 1
    state="$(systemctl is-active "$APP_NAME" 2>/dev/null || true)"
    case "$state" in
      active)
        sleep 2
        if [ "$(systemctl is-active "$APP_NAME" 2>/dev/null || true)" = "active" ]; then
          log "service is running: ${APP_NAME}"
          break
        fi
        ;;
      failed)
        systemctl status "$APP_NAME" --no-pager -l >&2 || true
        fatal "systemd service failed to start: ${APP_NAME}"
        ;;
    esac
  done
  [ "${state:-}" = "active" ] || fatal "timed out waiting for systemd service: ${APP_NAME}"
  log "installed systemd service: $SERVICE_FILE"
}

write_upgrade_service() {
  if [ "$ENABLE_UPGRADE" != "true" ]; then
    rm -f "$UPGRADE_SERVICE_FILE"
    return
  fi
  local upgrade_backup_dir
  upgrade_backup_dir="$(dirname "$RUNTIME_DIR")/vboard-node-backups"
  mkdir -p "$upgrade_backup_dir"
  chmod 0700 "$upgrade_backup_dir"
  cat >"$UPGRADE_SERVICE_FILE" <<EOF
[Unit]
Description=VBoard Node Controlled Upgrade
After=network-online.target
Wants=network-online.target

[Service]
Type=oneshot
User=root
ExecStart=${INSTALL_DIR}/${APP_NAME} --apply-upgrade ${RUNTIME_DIR}/upgrade-request.json
NoNewPrivileges=true
PrivateTmp=true
ProtectHome=true
ProtectSystem=full
ProtectKernelTunables=true
ProtectKernelModules=true
ProtectControlGroups=true
RestrictSUIDSGID=true
LockPersonality=true
ReadWritePaths=${INSTALL_DIR} ${RUNTIME_DIR} ${upgrade_backup_dir}
EOF
  chmod 0644 "$UPGRADE_SERVICE_FILE"
}

show_status() {
  refresh_paths
  printf 'vboard-node status\n'
  printf '  binary:  %s\n' "${INSTALL_DIR}/${APP_NAME}"
  printf '  config:  %s\n' "$ENV_FILE"
  printf '  service: %s\n' "$SERVICE_FILE"
  if [ -x "${INSTALL_DIR}/${APP_NAME}" ]; then
    "${INSTALL_DIR}/${APP_NAME}" --help >/dev/null 2>&1 &&
      printf '  binary check: ok\n' ||
      printf '  binary check: failed\n'
  else
    printf '  binary check: missing\n'
  fi
  if command -v systemctl >/dev/null 2>&1 && [ -f "$SERVICE_FILE" ]; then
    systemctl status "$APP_NAME" --no-pager || true
  fi
}

uninstall_node() {
  need_root
  refresh_paths
  systemctl disable --now "$APP_NAME" >/dev/null 2>&1 || true
  rm -f "$SERVICE_FILE" "$UPGRADE_SERVICE_FILE" "${INSTALL_DIR}/${APP_NAME}"
  systemctl daemon-reload >/dev/null 2>&1 || true
  log "service and binary removed; configuration retained at $CONFIG_DIR"
}

main() {
  parse_args "$@"
  refresh_paths

  case "$ACTION" in
    status)
      show_status
      return
      ;;
    uninstall)
      uninstall_node
      return
      ;;
    upgrade)
      load_existing_config
      if [ -z "$BINARY_URL" ] && [ -z "$RELEASE_BASE" ]; then
        fatal "upgrade requires --binary-url or --release-base"
      fi
      ;;
    install) ;;
    *) fatal "unsupported action: $ACTION" ;;
  esac

  validate_args
  need_root
  command -v curl >/dev/null 2>&1 || fatal "curl is required"
  command -v systemctl >/dev/null 2>&1 || fatal "systemd is required"

  stage_binary
  backup_existing_state
  install_staged_binary "$STAGED_BINARY"
  ensure_sing_box
  write_env_file
  self_test
  write_systemd_service
  ROLLBACK_READY="false"
  log "${ACTION} complete"
  log "status: systemctl status ${APP_NAME} --no-pager"
  log "logs: journalctl -u ${APP_NAME} -f"
}

main "$@"
